apps/my_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
	url(r'^login$', views.login),
    # url(r'^success$', views.success, name='success'),
    url(r'^logOut$', views.logOut, name='logOut'),
	url(r'^toItems/(?P<id>\d+)$', views.toItems, name='toItems'),
    url(r'^addItem$', views.addItem, name='addItems'),
	url(r'^viewItems$', views.viewItems, name='viewItems'),
	url(r'^addToMyItem/(?P<item_id>\d+)$', views.addToMyItem, name='addToMyItem'),
	url(r'^deleteItem/(?P<item_id>\d+)$', views.deleteItem, name='deleteItem'),
	url(r'^deleteFromD/(?P<id>\d+)$', views.deleteFromD, name='deleteFromD'),
]

cdExam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.my_app.urls', namespace='my_app')),
    url(r'^admin/', admin.site.urls),
]

apps/my_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class User(models.Model):
    firstName = models.CharField(max_length= 101)
    lastName = models.CharField(max_length= 101)
    email = models.CharField(max_length= 101, unique= True)
    password = models.CharField(max_length=101)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Item(models.Model):
    itemName = models.CharField(max_length= 101)
    creator = models.ForeignKey(User, related_name='creator')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Addition(models.Model):
    user = models.ForeignKey(User, related_name='additions') 
    item = models.ForeignKey(Item, related_name='additions')
    created_at= models.DateField(auto_now_add=True)
    updated_at= models.DateField(auto_now=True) 

apps/my_app/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from models import *
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def index(request):
    return render(request, 'my_app/index.html')
def register(request):
    if request.method=='POST':
        firstName= request.POST['firstName']
        lastName= request.POST['lastName']
        email= request.POST['email']
        password= request.POST['password']
        conPassword= request.POST['conPassword']
        isValid=True
        minVal= 3
        maxVP= 8
    if len(request.POST['firstName']) < minVal:
        messages.error(request, 'Name needs to be at least 3 characters!')
        isValid = False
    if len(request.POST['lastName']) < minVal:
        messages.error(request, 'Last Name needs to be at least 3 characters!')
        isValid = False
    if len(request.POST['email']) < minVal:
        messages.error(request, 'Email is required!')
        isValid = False
    if request.POST['email'] != email:
        messages.error(request, 'Email is already registered!')
        isValid = False
    if len(request.POST['password']) < minVal:
        messages.error(request, 'Password is required!')
        isValid = False
    if request.POST['conPassword'] != password:
        messages.error(request, 'Password confirmation failed!')
        isValid = False
    if not isValid:
        return redirect('/')

    if request.POST['conPassword'] == password:
        try:
            user=User.objects.create(firstName=firstName, lastName=lastName, email=email, password=password )
        except IntegrityError:
            messages.error(request, 'This Email is already registered!')
            return redirect('/')
        request.session['user.id']= user.id
    return redirect('my_app:viewItems')        
    # return render(request,'myApp/success.html')

def login(request):
    if request.method=='POST':
        email = request.POST['email']
        password= request.POST['password']
        isValid= True
        minVal= 3
    if len(request.POST['email']) < minVal:
        messages.error(request, 'Email is required!')
        isValid = False
    if len(request.POST['password']) < minVal:
        messages.error(request, 'Password is required!')
        isValid = False
    try:
        User.objects.get(email=request.POST['email'], password= request.POST['password'])
    except ObjectDoesNotExist:
        messages.error(request, "Email and Password don't match!")
        isValid = False
    else:
        messages.error(request, " ")

    if not isValid:
        return redirect('/')
    else:
        request.session['user.id'] = (User.objects.get(email=request.POST['email'])).id
        return redirect('my_app:viewItems') 
        # return render(request, 'my_app/success.html')

# def success(request):
#     if 'user.id' in request.session.keys():
#         user= User.objects.get(id=request.session['user.id'])
#     context={
#         'user': user
#     }
#     return render(request, 'my_app/success.html', context)

def viewItems(request):
    user= request.session['user.id']
    context={
        'items': Item.objects.all().exclude(additions__user_id=user),
        'myItems': Addition.objects.filter(user_id=user),
        'additions': Addition.objects.all(),
        'user': User.objects.get(id=request.session['user.id'])
    }
    return render(request, 'my_app/success.html', context)
    # return render(request, 'my_app/success.html', context)

def logOut(request):
    request.session.clear()
    messages.success(request, 'Successfully logged out')
    return redirect('/')

def addItem(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user.id'])
        itemName = request.POST['itemName']
        isValid=True
        minVal= 3
        if len(request.POST['itemName']) < minVal:
            messages.error(request, 'COVFEFE! Your Wishlist Item must contian at least 3 characters!')
            isValid = False
        if not isValid:
            return redirect('my_app:viewItems')
        else:
            Item.objects.create(itemName=itemName, creator = user)
            messages.error(request, "HOPE YOUR WISH COMES TRUE")
    return redirect('my_app:viewItems')

def toItems(request, id):
    user= request.session['user.id']
    context={
        'item': Item.objects.get(id=id),
        # 'myItems': Addition.objects.filter(user_id=user),
        'additions': Addition.objects.filter(item_id=id)
    }
    return render(request, 'my_app/show.html', context)

def addToMyItem(request, item_id):
    Addition.objects.create(item_id=item_id, user_id=request.session['user.id'])            
    return redirect('my_app:viewItems')

def deleteItem(request, item_id):
    item= Addition.objects.get(item_id=item_id, user_id=request.session['user.id'])
    item.delete()
    return redirect('my_app:viewItems')

def deleteFromD(request, id):
    item= Item.objects.get(id=id)
    item.delete()
    return redirect('my_app:viewItems')    

apps/my_app/templates/my_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>CODING DOJO EXAM</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous">
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
        <!-- <script src="main.js"></script> -->
    </head>    
    <body>
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <div id="main" class="card">
                        {% for message in messages%}
                            <p> {{message}} </p>
                        {% endfor %}
                        <div class="card-content">
                            <span class="card-title">REGISTER</span>            
                            <form action="register" method="POST">
                                {% csrf_token %}
                                <label for="firstName">First Name:</label>
                                <input type="text" name="firstName">
                                <br>
                                <label for="lastName">Last Name:</label>
                                <input type="text" name="lastName">
                                <br>
                                <label for="email">Email:</label>
                                <input type="text" name="email">
                                <br>
                                <label for="password">Password:</label>
                                <input type="password" name="password">
                                <br>
                                <label for="conPassword">confirm PW:</label>
                                <input type="password" name="conPassword">
                                <br>
                                <input type="submit"  name="register" value="REGISTER">
                            </form>
                        </div>
                    </div>
                    <div id="main" class="card">
                        <div class="card-content">
                            <span class="card-title">LOGIN</span>
                            <form action="login" method="POST">
                                {% csrf_token %}
                                <label for="email">Email:</label>
                                <input type="text" name="email">
                                <br>
                                <label for="password">Password:</label>
                                <input type="password" name="password">
                                <br>
                                <input type="submit"  name="login" value="LOGIN">    
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

apps/my_app/templates/my_app/show.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>CODING DOJO EXAM</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <script src="main.js"></script> -->
    </head>
    <body>
        <a href="{% url 'my_app:logOut' %}">Logout</a> |
        <a href="{% url 'my_app:viewItems' %}">To Wish List</a>
        <h1>{{item.itemName}} </h1>
        <h2>Users who added this product/item under thir wish list:</h2>
        {% for add in additions %}
            <h3>{{add.user.firstName}} </h3>
        {% endfor %}
    </body>
</html>

apps/my_app/templates/my_app/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>CD EXAM</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
        <!-- <script src="main.js"></script> -->
    </head>
    <body>
        <a href="{% url 'my_app:logOut' %}">Click here to logout</a> 
        <h1>Hello, {{user.firstName}}</h1>  
        <h1>Your Wish List</h1>
        <h3>  (click on the item to Display it)  </h3>
        <table>
            <thead>
                <tr>
                    <th>ITEM </th>  
                    <th>DATE ADDED</th>
                    <th>ADDED BY</th>
                    <th>ACTIONS</th>
                </tr>
            </thead>
            <tbody>
            {% for addition in myItems %}
                <tr>
                    <td><a href="{% url 'my_app:toItems' id=addition.item.id %}">{{addition.item.itemName}}</a></td>
                    <td>{{addition.item.created_at}}</td>
                    <td>{{addition.item.creator.firstName}}
                    {%  if addition.item.creator.id == user.id %}
                        <td><a href="{% url 'my_app:deleteFromD' id=addition.item.id %}">Delete Item</a></td>
                    {% else %}
                        <td><a href="{% url 'my_app:deleteItem' item_id=addition.item.id %}">Remove from my Wishlist </a></td>
                    {% endif %}

                </tr>
            </tbody>
            {% endfor %}
        </table>
        <h1>Other User's Wish List</h1>
        <form action="/addItem" method='POST'>
        {% csrf_token %}
            <input type="text" name="itemName" value="" class="">
            <input type="submit" name="submit" value="Add Item" class="">
        </form>
        
        {% for message in messages%}
            <p>   {{message}} </p>
        {% endfor %}
        

        <h3>  (click on the item to add to your Wishlist)  </h3>
        <table>
            <thead>
                <tr>
                    <th>Item </th>  
                    <th>DATE ADDED</th>
                    <th>ADDED BY</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                {% for item in items %}
                    <td><a href="{% url 'my_app:addToMyItem' item_id=item.id %}">{{item.itemName}}</a></td>
                    <td>{{item.created_at}}</td>
                    <td>{{ item.creator.firstName}}</td>               
                </tr>
            </tbody>
                {% endfor %}
        </table>    
    </body>
</html>